#!/usr/bin/env bash

file=$(realpath "${BASH_SOURCE[0]}")
dir=$(dirname "$file")
export ZEEKPATH=$dir/share/zeek:$dir/share/zeek/policy:$dir/share/zeek/site
export ZEEK_PLUGIN_PATH=$dir/lib/zeek/plugins
exec "$dir/bin/zeek" "$@"
